name: publish trrex package to PyPI

on:
  workflow_dispatch:
  release:
    types: [created]


jobs:
  publish:
    name: publish trrex to PyPI
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.19"

      - name: install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv build

      - name: Smoke test (wheel)
        run: uv run --isolated --no-project -p 3.12 --with dist/*.whl pytest tests/test_basic_functions.py

      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project -p 3.12 --with dist/*.tar.gz pytest tests/test_basic_functions.py

      - name: publish package
        run: uv publish --trusted-publishing always
