name: publish trrex package to PyPI

on:
  workflow_dispatch:
  release:
    types: [created]


jobs:
  publish:
    name: publish trrex to PyPI
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: publish package
        run: |
          uv build
          uv publish --trusted-publishing always
